server:
  port: 4544
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  data:
    redis:
      host:
      port:
      username:
      password:

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 5397e5b5bfb8d92a4bdc0636634328ba
            client-secret: FviuK7zk0KQz9lsEUv54kcb3tSbbfUsM
            redirect-uri: http://localhost:4544/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname,profile_image,account_email
            client-authentication-method: client_secret_post
          naver:
          google:
        provider:
          kakao:
          naver:

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:freemarket'
    username: free
    password: free
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: trace
    database-platform: org.hibernate.dialect.H2Dialect