server:
  port: 4544
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jwt:
    secret: ENC(GJeIVh04lFNRkVsaNC72Rdm7lOFvjKte+khorLQdxW2Hcqc6pcHaiNi5OEDB/FX6kwNglto5TN/lpVQk9gIQkOhAdjOCycFq4j2n726IFAI=)
    access-duration: 60000
    refresh-duration: 86400000

  data:
    redis:
      host: ENC(MjarGGvBnGJ91MjwENopxWZOsGED5UFvFiBY6FZk+KY=)
      port: 6379
      database: 0
      username: ENC(LYZc+YsS3ifxd7J9/D4aaA==)
      password: ENC(dXTenGyTCeq1/hMlBAxWFw==)

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ENC(3xLlVKBgDlTCM0Be2m9njpr90kHo5LTiPV6UjjRs0gbk4NdInQ6OM6+4LZmBiGbO)
            client-secret: ENC(BQBXYZgUV5lWa6SbNEgSzL3xrK+Qgz4W7iYJFkdOTVowAhiLiVLuTI1wY8wvmjtU)
            redirect-uri: https://freeapi.devsj.site/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname,profile_image,account_email
            client-authentication-method: client_secret_post
          naver:
            client-name: naver
            client-id: ENC(HXgTtWJy2iVTTGiRaVH92dmXwrHkBPlYX4afBhTs7I0=)
            client-secret: ENC(X1vkWw0hd/r/++SWaMCoJOih2hOxYwQU)
            redirect-uri: https://freeapi.devsj.site/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,nickname,profile_image
            client-authentication-method: client_secret_post
          google:
            client-name: google
            client-id: ENC(+vkikOV6JaW+l2rqAf0woV5kZgXJkorzgzhXZ9wzlXHg4gJljsTN19JMFTjzSWH49klp6t6jLKl7zwtwV0cMA7iizpr1GddSjRHv5zEm3Uo=)
            client-secret: ENC(Rk7AoDHcQweHUdNNRrXbTJMWzZFJW/RMYMR+Q/df+Wt5G26u5cfBfOLgnRQSv7OP)
            redirect-uri: https://freeapi.devsj.site/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  datasource:
    driver-class-name: org.h2.Driver
    url: ENC(OnwTxgnQ+6j00RJCiayYQC/FZ3zIztYWkwLnlH6uh7c=)
    username: ENC(wSDva3PJXYOsIUs45hW7Tg==)
    password: ENC(kNSKpYyIf+YwFcLR1mSExg==)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show_sql: true
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: trace
    database-platform: org.hibernate.dialect.H2Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: freemarketofficial58@gmail.com
    password: ENC(fGu34GaIV/gfZNM6QiEBcCbG+oWkezuhL/fVLHHjchA=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

springdoc:
  swagger-ui:
    path: /swagger.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.api.freemarket
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD:defaultPassword}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    string-output-type: base64