server:
  port: 4544
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jwt:
    secret: ENC(1+OKpwlQGwCjgRs9co6vfmr/jsrpOyZpjq14sFT7MYRtMx/Z7RaYFfJIUBqyBOn572y42WgXn3tr/0GI8KohVycfiFLUKcOBKGRVe58cN+I=)
    access-duration: 60000
    refresh-duration: 86400000

  data:
    redis:
      host: ENC(SsMHpmt+PPyEeRw73kZ9ePXiZiUOUhzj)
      port: 6379
      database: 0
      username: ENC(zSxTQUK+aGLSGzw0c+bS2Q==)
      password: ENC(cVTwkjdYVSrdaI6YnBC5OQ==)

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ENC(FliPRzwcUFcbPW2TGQnEBcTBd6UKg3qlbJ1VAs/BzjF59v3o7qg5vFJkx8w7RCvd)
            client-secret: ENC(ad/1mXdXHcq6m4Zm9AjtsNylMB2oKneCFZw6HLuQVtOJ3nIfFclr40cLs5pX05P+)
            redirect-uri: http://localhost:4544/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname,profile_image,account_email
            client-authentication-method: client_secret_post
          naver:
            client-name: naver
            client-id: ENC(H3sOvXhcqSP2AudQH/+0F/mk7qeDm/TqlsqbiAHA+ro=)
            client-secret: ENC(mSiYvy40UKDnb+Sb4efjEwwhFGF0DDUu)
            redirect-uri: http://localhost:4544/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,nickname,profile_image
            client-authentication-method: client_secret_post
          google:
            client-name: google
            client-id: ENC(VaJzjsvQ1Ylxz5g+OPBaSfHWu00cM6xlEkClFkFqReXJXblydssm4UXTkWfLDtjUHwgHIbrSdxPjrlyfh+wL/UnT342KyGBnsGrlxTWjBRk=)
            client-secret: ENC(XmXLZhw6bNzkbDcVlJSw0FfrykqAjAacgVoxc5/jBGjXQVzW2ErPGxvOyhHV1F5D)
            redirect-uri: http://localhost:4544/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  datasource:
    driver-class-name: org.h2.Driver
    url: ENC(fmVO37MlAaX7X304hiEPDBtFtixzLAdGvK9dKfXJtLA=)
    username: ENC(208e8BD9pz/iVCcEJXt+0Q==)
    password: ENC(J7ntg12PVdFCyd10BOJg5w==)
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show_sql: true
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: trace
    database-platform: org.hibernate.dialect.H2Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: freemarketofficial58@gmail.com
    password: ENC(kBi9Ur7SbySKu5ZCCmVAwZyOU/Q2yLAJYEBDchBPPVk=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

springdoc:
  swagger-ui:
    path: /swagger.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.api.freemarket
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    string-output-type: base64