server:
  port: 4544
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  data:
    redis:
      host: localhost
      port: 6379
      #username:
      #password:

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 5397e5b5bfb8d92a4bdc0636634328ba
            client-secret: FviuK7zk0KQz9lsEUv54kcb3tSbbfUsM
            redirect-uri: http://localhost:4544/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname,profile_image,account_email
            client-authentication-method: client_secret_post
          naver:
            client-name: naver
            client-id: YGr2FqhHn4_wQ1_8wvs7
            client-secret: TzMBhQfSkJ
            redirect-uri: http://localhost:4544/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,nickname,profile_image
            client-authentication-method: client_secret_post
          google:
            client-name: google
            client-id: 82131316117-dginrgt07m74sns9nv5errh3v3bd886q.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:4544/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:freemarket'
    username: free
    password: free
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show_sql: true
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: trace
    database-platform: org.hibernate.dialect.H2Dialect